getify/You-Dont-Know-JS

up & going/ch3.md
- “Not topic” to “No topic”
- “adn” to “and”
=> typo fixes

async & performance/ch3.md
Just adds a missing var in the example for consistency.
=> async+perf: add missing var in example

async & performance/ch4.md, async & performance/ch5.md, async & performance/ch6.md
Corrects some minor typos in chapter 4, 5, and 6 in the "Async and Performance" title.
Thanks for the great resource. Cheers!
=> Typo correction for A&P chapters

async & performance/ch3.md
Noticed this instance was inconsistent with the style of other instances.
=> Changed Promise.race([..]) to Promise.race([ .. ]) to be consistent with other usages

types & grammar/ch4.md
=> Fix 'accross'

es6 & beyond/ch2.md
Doing `typeof` in the _temporal dead zone_ throws a `ReferenceError`, not a `TypeError`.
```shell
➤ node --harmony t.js
undefined
/Users/isaac/code/temp/t.js:4
console.log( b );   // ReferenceError!
^
ReferenceError: b is not defined
at Object.<anonymous> (/Users/isaac/code/temp/t.js:4:16)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3
➤ node --harmony t.js
undefined
/Users/isaac/code/temp/t.js:5
if (typeof b === "undefined") {
^
ReferenceError: b is not defined
at Object.<anonymous> (/Users/isaac/code/temp/t.js:5:14)
at Module._compile (module.js:460:26)
at …
```
=> Fix error being thrown on typeof

up & going/ch2.md
Noticed the 'D' in `getElementById` was capitalized. This should be lowercase.
=> Fix typo for DOM API call `document.getElementById`

es6 & beyond/ch3.md
First of all, I just wanted to say this is such an incredible book for any Javascript engineer, thank you so much for making this resource available for free @getify.
In your hand transpiled version of the generator, there is a `console.log( x )` that is expected to fire during `case 1`, but is not displayed in the test output
Expected:
Fix:
=> es6+beyond: ch3, fixed typo in 'transpiling a generator'

es6 & beyond/ch2.md
Tiny little typo in link to post on Unicode regex in ES6.
=> Fix link to Unicode regex post

es6 & beyond/ch7.md
This is the `revocable` function that returns *proxy* and *revoke*.
=> Fix mistake in ch.7

es6 & beyond/ch3.md
Just a couple of typos in the third chapter of the ES6 title.
=> Fix a couple of typos

scope & closures/ch5.md
Omits the first occurrence of "be" from the following sentence on line 580: "**Note:** Separate files **"foo.js"** and **"bar.js"** would be need to be created..."
=> Corrects minor typo.

this & object prototypes/ch3.md
Thanks for writing this excellent book. There is a minor typo in the linked section. "The" is unnecessary before "Chapter 5".
"We'll come back to the important differences between these two operations in the Chapter 5 when we explore [[Prototype]]s in detail."
https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch3.md#existence
=> Update ch3.md - remove unnecessary "the"

this & object prototypes/ch1.md
The snippet just simply logs `undefined` to the console, rather than throws a ReferenceError. In your case, both `this` keyword in function `foo` and `bar` refers to the global object, namely `window` in non-strict mode. Since no variable named `a` is defined in global scope, `console.log(this.a)` will logs `undefined`!
=> Correct the result of code snippet

this & object prototypes/ch2.md
avoids confusion that "applied" might begin an adjectival clause
=> verbal agreement - applies/points

types & grammar/ch4.md
I think what happened here is that some over-eager spell-checker liked "equitable" better.
But "equitable" seems to mean "characterized by equity or fairness; just and right; fair;
reasonable", and "equatable" (as in "coming up as equal in an equality comparison") makes
a lot more sense here. A third "equatable" earlier in the first paragraph seems to support
this, too.
=> fix two s/equitable/equatable/ typos

up & going/README.md
Other books have working link, this one doesn't have it.
=> Added link for purchase/download of the first book

es6 & beyond/ch8.md
Typo in Es6&beyond, ch8, line 403: "signficantly" => "significantly".
Thanks for the thorough material, best reference for JS out there!
=> Fix typo in ch8: "signficantly" => "significantly"

es6 & beyond/ch3.md
Typo on line 1476: "additionaly" => "additionally". Thanks again for the great material.
=> Fix typo in ch3 (es6 & beyond)

es6 & beyond/ch2.md
Line 1153: "mechansim" => "mechanism"
Line 2080: "intepretation" => "interpretation"
Line 2522: "verison" => "version"
=> Fix typos in ch2 (es6 & beyond)

async & performance/ch5.md
Line 48: "theaded" => "threaded"
Line 238: "perfomance" => "performance"
Line 248: "compliation" => "compilation"
Line 362: "resposive" => "responsive"
=> Fix typos in ch5 (async & performance)

async & performance/ch4.md
Line 760: "capabililty" => "capability"
Line 2178: "unitialized" => "uninitialized"
=> Fix typos in ch4 (async & performance)

es6 & beyond/ch7.md
Line 287: "behaivor" => "behavior"
Line 872: "programmtic" => "programmatic"
Line 1170: "limitiation" => "limitation"
Line 1195: "reusabilty" => "reusability"
=> Fix typos in ch7 (es6 & beyond)

types & grammar/ch5.md
Line 459: "rougly" => "roughly"
Line 1031: "assigment" => "assignment"
=> Fix typos in ch5 (types and grammar)

types & grammar/ch2.md
I am not an English major, but it seemed like this sentence was missing a “to”. Let me know if it should be written another way. Thanks!
=> Fix Typo in Ch 2 of Types & Grammer

async & performance/ch2.md
The example will always log to `console.error`.
A null value must be pushed onto the front of the list in the success case so it will fail
the `err` clause in the callback.
=> Async & Performance, Ch 2: `timeoutify()` example bug

scope & closures/ch3.md
This fix alters one word that potentially causes misinterpretation. The first time I read this sentence, I thought it meant: "The omission of a name is often helpful in providing more readable/understandable code." I quickly realized that this is not the case, and I believe this potential confusion can be avoided by changing "which" to "that."
=> (fix) change "which" to "that"

scope & closures/ch5.md
I don't think timer is an anonymous function in this case since it has a name.
=> Reworded so function timer is not referred to as anonymous

this & object prototypes/ch5.md
It seems to me that the word "property" doesn't need to be at both ends of the `Foo.prototype` text. Leaving the second one flows better when reading, I think.
=> Remove extraneous word "property"

async & performance/ch6.md
Spelling mistake - `optimial` > `optimal`
=> Fix typo in Async & Performance/Ch6

this & object prototypes/ch4.md
"classes" is plural, even though it is quoted.
http://www.quickanddirtytips.com/education/grammar/oddness-when-you-start-a-sentence-with-there-is
=> fix grammar in "this & object prototypes" chap. 4

types & grammar/ch2.md
99.9% sure this is the only way to spell 'exercise' in both the American and British standards of English.
=> Corrected spelling error line 221 in types & grammar/ch2.md

up & going/ch1.md
line 695 [...] but code -only- in `outer()` has access only to `a`
=> ch1.md unnecessary word (only)

es6 & beyond/ch7.md
val already contains onlu lower cases because it was forced few lines above.
=> Unnecessary usage of toLowerCase().

es6 & beyond/ch7.md
`JSON.stringification(..)` here is formated as formal method of JSON object. It should be changed to `JSON.stringify(..)` as this method actually exists or change to informal, normal text `JSON stringification`.
=> There doesn't exist JSON.stringification(..).

scope & closures/ch5.md
Just a simple word swap. Anticlimactic is a word meaning without a climax, whereas climatic will refer to weather/climate. 
P.S. Thanks so damn much for this book series! I love it.
=> Replace: anti-climatic with anticlimactic

scope & closures/apB.md
[^note-let_er]: [let-er] will not display anything as a space is required after the text 'let-er'. I have added this space and the note now appears at the bottom of the page.
=> Fix missing note

scope & closures/ch3.md
I can't see any reason for the extra pair of parentheses being there
=> Unnecessary parentheses

es6 & beyond/ch6.md
There's a typo in the `endsWith(..)` method name, pretty self explanatory.
=> Fix typo in ch6.md of "ES6 & Beyond"

types & grammar/ch4.md
JS syntax highlighting was missing in the snippet: 
```
var a = "3.14";
var b = a - 0;
b; // 3.14
```
=> "types & grammar" ch 4: Add js syntax highlighting

this & object prototypes/ch3.md
This PR adds a missing "how" to the description of the iteration helpers' behavior. 
"Each of these helpers accepts a function callback to apply to each element in the array, differing only in *how* they respectively respond to a return value from the callback."
=> Add missing word

es6 & beyond/ch2.md
Small word order change.  Original text:
"is... very not ideal, performance wise."
Changed to read:
"is... not very ideal, performance wise."
=> es6+beyond: ch2.md, fixing word order issue

async & performance/ch3.md
"swallow" had inconsistent casing from its list, so this fixes that error.
=> Make a letter uppercase to match list style

async & performance/apB.md
@swannodette's website returns "page does not exist" if `/` appended at the end of the url
=> Fix hyperlink to referred article

README.md
Recently the links on the README to the various titles within the repository became broken. This commit replaces spaces in the subdirectory names with "\%20" which causes Github markdown to correctly display the link and for the link to properly direct to the appropriate subdirectory. (The links were working fine as of a month ago when last I checked, I assume that Github recently changed how they process links in markdown and what once worked, ceased to).
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line). I really did read the contributing guidelines. There didn't seem to be an issue for this and it seemed more a functional tweak than a typo that could be safely …
=> Fix broken links in Titles section of README.

types & grammar/apA.md
The traceur-compiler getting started URL was missing a hyphen.
=> Update traceur getting started URL

this & object prototypes/ch5.md
Continuous `` doesn't interpret correctly because there's another one outside.
=> Fixed markdown syntax

es6 & beyond/ch7.md
Links pointing to _people.mozilla.org_ are currently being used. However, _people.mozilla.org_ has been discontinued and is offline.
The links were pointing to ES6/ES2015 sections. I updated the links to use **ecma-international.org**. Each link should point to its corresponding section on the specification
=> ES6 & Beyond (ch7.md): Broken links on Regex section

async & performance/ch3.md
Removes characters `a ` in line 1486 of async & performance chapter.
=> fix typo, chapter 3, line 1486

types & grammar/ch5.md
After removing the typo, the latter part of the sentence is still a little unclear: if either form works, then will most developers prefer the shorter form because it's shorter? Or is it better in some other way?
=> minor typo: remove 'be' from 'be become'

scope & closures/ch3.md
"as properties off that object" -> as properties of that object
=> typo: off -> of

README.md
The previous image was not available anymore. Replaced it with a direct link to the one on [https://www.patreon.com/brand/downloads](https://www.patreon.com/brand/downloads)
=> Fixed missing Patreon image
