getify/You-Dont-Know-JS

up & going/foreword.md

First draft of foreword for this title

Adding forward for Up & Going

---

es6 & beyond/ch2.md

Corrected misspelled ReferenceError on line 99.

Corrected misspelled ReferenceError on line 99

---

async & performance/ch3.md

I'm fairly certain this was supposed to be a comment

Resolved missing comment

---

es6 & beyond/ch7.md

Fixed typo in proxy assignment.

Updated Proxy assignment

---

this & object prototypes/ch3.md

V. minimal - just wanted to increase indent of the comment marking the type of StrObject as 'object', so that it lines up with the other comments.

Change in indenting.

---

es6 & beyond/ch2.md

es6+beyond: revise const GC admonition

---

scope & closures/ch2.md

Just a trivial edit of the output of a console.log( foo, bar) which will not have the comma in the output of the log()

extremely trivial tweak of a comment

---

this & object prototypes/ch2.md

Change the type of entity from male to neuter because it's about the `function`

Fix typo from `he` to `it`

---

es6 & beyond/ch7.md

-Updated  "it's time to start leveraging these powerfu meta programming capabilities to push the language further!" on line 1280 to "it's time to start leveraging these powerful meta programming capabilities to push the language further!"

issue 448, updating mis-type

---

async & performance/ch1.md
types & grammar/ch4.md

A couple of fixes for misspellings I found while reading.

Corrected spelling of two words.

---

es6 & beyond/ch5.md

Just a typo fix. 'is an a collection' -> 'is a collection'

Update ch5.md - minor typo

---

this & object prototypes/ch5.md

Small language addition for improved readability

"this & object prototypes": update ch5

---

this & object prototypes/ch3.md

End question with question mark

---

this & object prototypes/ch5.md

in line 445 it's difficult to see, but I've changed "**But, it used**" to "**But, it uses**"

minor edits: verb agreement, temporal consistency

---

this & object prototypes/ch4.md

fixed typo

---

this & object prototypes/ch3.md

Adding missing variable in example

---

async & performance/ch1.md

Line 119: "statment" => "statement"

Fix typos in ch2 (async & performance)

---

types & grammar/ch5.md

Line 46: "statments" => "statements"

Fix typo ch5 (types and grammar)

---

es6 & beyond/ch7.md

Line 884: "properities" => "properties"
Thanks again for your superb material!

Fix typo ch7 (es6 & beyond)

---

async & performance/ch4.md

The only change I made was fixing the spelling typo:
1) Change from that to that's
No other changes made.

Fix spelling typo

---

types & grammar/ch1.md

fixes two minor grammatical errors

update ch1.md in types & grammar

---

types & grammar/ch2.md

corrects minor grammatical error of improper case

update ch2.md in types & grammar

---

es6 & beyond/ch3.md

I'm not certain, that this is proper fix from Your POV but I was trying to not include any other features here and print plain object, that generator actually returned.

fixing value returned from generator

---

es6 & beyond/ch6.md

find() has exactly the same note above.

Fixing note about passing this to findIndex().

---

async & performance/ch4.md

Add `return` statement in order to be consistent with the previous example for `function bar()`

Add a return statement

---

types & grammar/ch4.md

Changed `an generic` to `a generic`

Fix grammar error

---

README.md

The logo for Patreon missing which makes it difficult to know how to contribute to the work on this series of books

Update Missing Patreon Logo

---

README.md

Link Patreon logo to the getify Patreon page

---

async & performance/apB.md

I believe there is a small mistake/typo in this ASQ.iterable() example from _async & performance > appendix B_

fix ASQ.iterable() example in apB

---

types & grammar/ch5.md

It's not a question, but a noun clause.

Grammar - why clause SV order

---

async & performance/ch1.md
async & performance/ch2.md
async & performance/ch3.md
async & performance/ch4.md

**Yes, I promise I've read the [Contributions Guidelines](CONTRIBUTING.md)** 😄

Fix some typos in Async & Performance

---

this & object prototypes/ch3.md

typo: mistakingly -> mistakenly

---

scope & closures/ch3.md

Optimized wording in Chinese

---

this & object prototypes/ch2.md

Fixed minor typo

---

this & object prototypes/ch2.md

Optimized wording and sample code formatting

---

es6 & beyond/ch2.md

Typo in ch2: prinicple --> principle

---

types & grammar/ch4.md

remove unnecessary indents

---

README.md

The badge conforms to new branding of patreon.com and is taken from the
official [media kit](https://www.patreon.com/brand/guidelines).
The badge comes in three sizes. I have used the medium one. Apart from the badge, there are artifacts that involve the logo. Feel free to ask for any changes you might prefer.

Update the 'Become a Patron' badge

---

this & object prototypes/ch5.md

Fixes minor typo referenced in issue: #1279

Minor typo

---

scope & closures/apB.md

Updated Google Tracer tool link since former was deprecated/broken

---

up & going/ch2.md

* added missing 'one' to sentence
* removed unneccessary comma

Grammar fixes

---

async & performance/ch3.md

fix typo, chapter 3, line 165
